name: Feature Request Form
description: Submit a feature request.
title: "[ENH]: "
labels: ["enhancement", "feature request"]
projects: []
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! Your suggestions help us improve.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com or GitHub username
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see implemented.
      placeholder: "Describe the feature here"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://github.com/privacera/paig/blob/main/docs/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true