name: Task
description: Assign a task to someone on the team.
title: "[TASK]: "
labels: ["task"]
projects: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the details below to create a new task.

  - type: textarea
    id: task-details
    attributes:
      label: Task Details
      description: Provide detailed information about the task.
      placeholder: "Describe what needs to be done"
    validations:
      required: true

  - type: input
    id: due-date
    attributes:
      label: Due Date
      description: When should the task be completed by? (optional)
      placeholder: "YYYY-MM-DD"
    validations:
      required: false

  - type: checkboxes
    id: priority
    attributes:
      label: Priority Level
      description: Select the priority level for this task.
      options:
        - label: Low
        - label: Medium
        - label: High

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://github.com/privacera/paig/blob/main/docs/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true