bedrock:
  embedding_model: "amazon.titan-embed-text-v1"
  model: "anthropic.claude-3-5-sonnet-20240620-v1:0"
  region: "us-east-1"


AI_applications:
  sales_model:
    implementation_class: "services.Bedrock_Application.BedrockClient.BedrockClient"
    vectordb:
      index_name: "sales_index"
      data_path: "securechat/sales/data"
      vector_type: "opensearch"

opensearch:
  user: "admin"
  password: "Paig2024@"
  hosts: "opensearch-node1:9200"